[package]
name = "ariel-os-log"
version = "0.5.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[package.metadata.feature-groups]
logging-facade.xor = { features = ["defmt", "log"] }
logging-transport.xor = { features = [
  "defmt-rtt",
  "logging-over-uart",
  "logging-over-usb",
] }

[dependencies]
ariel-os-debug = { workspace = true }
ariel-os-utils = { workspace = true, optional = true }
const-str = { workspace = true, optional = true }
critical-section = { workspace = true, optional = true }
defmt = { workspace = true, optional = true }
embassy-futures = { workspace = true, optional = true }
embassy-sync = { workspace = true, optional = true }
embassy-usb = { workspace = true, optional = true }
esp-hal = { workspace = true, optional = true }
featurecomb = { workspace = true }
log = { workspace = true, optional = true }
static_cell = { workspace = true, optional = true }

[features]
## Enables `defmt` as logging facade.
defmt = ["dep:critical-section", "dep:defmt"]
## Enables `log` as logging facade.
log = ["dep:ariel-os-utils", "dep:const-str", "dep:critical-section", "dep:log"]

# Logging transports.
debug-uart = ["dep:embassy-sync", "logging-over-uart"]
# `defmt-rtt` uses the debug channel as the logging transport, so it has to go
# through this crate.
defmt-rtt = ["ariel-os-debug/defmt-rtt"]
logging-over-uart = []
logging-over-usb = []
logging-over-generic-usb = [
  "dep:embassy-futures",
  "dep:embassy-sync",
  "dep:embassy-usb",
  "dep:static_cell",
]
logging-over-esp-jtag-serial = ["dep:embassy-sync", "dep:esp-hal"]
std = []

_test = []

[lints]
workspace = true
