[package]
name = "ariel-os-stm32"
version = "0.2.0"
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
ariel-os-stm32-mapping = { path = "../ariel-os-stm32-mapping" }
cfg-if = { workspace = true }
defmt = { workspace = true, optional = true }
embassy-embedded-hal = { workspace = true, optional = true }
embassy-executor = { workspace = true, default-features = false, features = [
  "arch-cortex-m",
] }
embassy-stm32 = { workspace = true, default-features = false, features = [
  "memory-x",
  "optfield",
  "rt",
  "time-driver-any",
  "unstable-pac",
] }
embedded-hal-async = { workspace = true }
embedded-io-async = { workspace = true, optional = true }
paste = { workspace = true }
portable-atomic = { workspace = true }
ariel-os-utils = { workspace = true }
ariel-os-embassy-common = { workspace = true }
ariel-os-random = { workspace = true, optional = true }
static_cell = { workspace = true }

[build-dependencies]
stm32-metapac = { version = "16.0.0", default-features = false, features = [
  "metadata",
] }

[features]
## Enables GPIO interrupt support.
external-interrupts = [
  "embassy-stm32/exti",
  "ariel-os-embassy-common/external-interrupts",
]

## Enables seeding the random number generator from hardware.
hwrng = ["dep:ariel-os-random"]

## Enables I2C support.
# Time-related features are required for timeout support.
i2c = [
  "dep:embassy-embedded-hal",
  "ariel-os-embassy-common/i2c",
  "embassy-stm32/time",
]

## Enables SPI support.
spi = ["dep:embassy-embedded-hal", "ariel-os-embassy-common/spi"]

## Enables UART support.
uart = ["dep:embedded-io-async", "ariel-os-embassy-common/uart"]

## Enables storage support.
storage = ["dep:embassy-embedded-hal"]

## Enables USB support.
usb = []

eth = []
eth-stm32 = ["dep:embassy-embedded-hal", "eth"]

## Enables defmt support.
defmt = ["dep:defmt", "embassy-stm32/defmt"]

## Enables the interrupt executor.
executor-interrupt = ["embassy-executor/executor-interrupt"]

_test = ["embassy-stm32/stm32wb55rg", "external-interrupts", "i2c", "spi"]
