[package]
name = "ariel-os-log-transport-driver"
version = "0.5.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[package.metadata.feature-groups]
logging-transport-driver.exactly-one = { features = ["dummy"] }

[dependencies]
ariel-os-hal = { workspace = true }
ariel-os-log = { workspace = true, features = ["custom-transport"] }
embassy-executor = { workspace = true }
embassy-sync = { workspace = true }
featurecomb = { workspace = true }

[features]

# Dummy driver, registers empty functions.
dummy = []

_test = []

[lints]
workspace = true
