include = "../ariel-os-cargo.toml"

[unstable]
# This is needed for cbindgen to work in no_std cross compiles.
features = ['all']

# This is needed so the "include" statement above works.
config-include = true


[env]
BINDGEN_EXTRA_CLANG_ARGS = "--sysroot=/usr/arm-none-eabi"
