[package]
name = "ariel-os-embassy"
version = "0.2.0"
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
const_panic.workspace = true
critical-section.workspace = true
linkme.workspace = true
portable-atomic.workspace = true
rand_core = { workspace = true, optional = true }
static_cell.workspace = true
cfg-if.workspace = true

embassy-embedded-hal = { workspace = true, optional = true }
embassy-executor = { workspace = true }
embassy-futures = { workspace = true }
embassy-hal-internal = { workspace = true }
embassy-net = { workspace = true, optional = true, features = [
  "medium-ethernet",
  "proto-ipv4",
] }
embassy-sync = { workspace = true }
embassy-time = { workspace = true, optional = true }
embassy-usb = { workspace = true, optional = true }

embedded-hal = { workspace = true }
embedded-hal-async = { workspace = true }

ariel-os-buildinfo = { workspace = true }
ariel-os-embassy-common = { workspace = true }
ariel-os-boards = { workspace = true }
ariel-os-hal = { path = "../ariel-os-hal" }
ariel-os-identity = { path = "../ariel-os-identity" }
ariel-os-threads = { path = "../ariel-os-threads", optional = true }
ariel-os-debug = { workspace = true }
ariel-os-macros = { path = "../ariel-os-macros" }
ariel-os-rt = { path = "../ariel-os-rt" }
ariel-os-random = { path = "../ariel-os-random", optional = true }
ariel-os-storage = { workspace = true, optional = true }
ariel-os-utils = { workspace = true }

heapless = "0.8.0"
once_cell = { workspace = true }
usbd-hid = { version = "0.8.2", optional = true }
trouble-host = { workspace = true, optional = true }

# ISA-specific
[target.'cfg(context = "cortex-m")'.dependencies]
embassy-executor = { workspace = true, default-features = false, features = [
  "arch-cortex-m",
] }

# Required for debug-over-uart.
[target.'cfg(context = "nrf")'.dependencies]
embassy-nrf = { workspace = true }
embedded-io-async = { workspace = true }

# Required for debug-over-uart.
[target.'cfg(context = "stm32")'.dependencies]
embassy-stm32 = { workspace = true }
embedded-io = { workspace = true }

[features]
## Enables GPIO interrupt support.
external-interrupts = [
  "ariel-os-embassy-common/external-interrupts",
  "ariel-os-hal/external-interrupts",
]
time = ["dep:embassy-time"]

## Enables I2C support.
i2c = [
  "dep:embassy-embedded-hal",
  "ariel-os-embassy-common/i2c",
  "ariel-os-hal/i2c",
]
## Enables SPI support.
spi = [
  "dep:embassy-embedded-hal",
  "ariel-os-embassy-common/spi",
  "ariel-os-hal/spi",
]

## Enables UART support.
uart = ["ariel-os-embassy-common/uart", "ariel-os-hal/uart"]

## Enables USB support.
usb = ["dep:embassy-usb", "ariel-os-hal/usb"]
usb-hid = ["dep:usbd-hid", "embassy-usb?/usbd-hid", "usb"]

# embassy-net requires embassy-time and support for timeouts in the executor
net = ["dep:embassy-net", "time"]
usb-ethernet = ["usb", "net"]

random = ["dep:ariel-os-random", "dep:rand_core"]
## Use a hardware RNG to seed into the ariel-os-random system-wide RNG
hwrng = ["ariel-os-hal/hwrng"]

## Enables support for DHCPv4.
dhcpv4 = ["embassy-net?/dhcpv4"]
## Enables support for TCP.
tcp = ["embassy-net?/tcp"]
## Enables support for UDP.
udp = ["embassy-net?/udp"]
## Enables support for DNS.
dns = ["embassy-net?/dns"]
## Enables support for mDNS.
mdns = ["embassy-net?/mdns"]
## Enables support for multicast (for both IPv4 and/or IPv6 if enabled).
multicast = ["embassy-net?/multicast"]

## Enable storage support [`ariel-os::storage`].
storage = ["dep:ariel-os-storage", "ariel-os-hal/storage", "time"]

debug-uart = []

wifi = []
wifi-cyw43 = ["ariel-os-hal/wifi-cyw43", "net", "wifi"]
wifi-esp = ["ariel-os-hal/wifi-esp", "net", "wifi"]

eth = []
eth-stm32 = ["ariel-os-hal/eth-stm32", "net", "eth"]

ble = [
  "dep:trouble-host",
  "ariel-os-embassy-common/ble",
  # Some HALs need hwrng to initialize the BLE stack.
  "hwrng",
  "ariel-os-hal/ble",
]
ble-cyw43 = ["ble", "ariel-os-hal/ble-cyw43"]
ble-peripheral = ["ble", "ariel-os-hal/ble-peripheral"]
ble-central = ["ble", "ariel-os-hal/ble-central"]

threading = ["dep:ariel-os-threads", "ariel-os-hal/threading"]
network-config-ipv4-static = ["network-config-override"]
network-config-override = []
override-usb-config = []
ble-config-static-mac = []

executor-single-thread = [
  "ariel-os-hal/executor-single-thread",
  "ariel-os-rt/executor-single-thread",
]
executor-interrupt = ["ariel-os-hal/executor-interrupt"]
executor-thread = ["threading", "ariel-os-embassy-common/executor-thread"]
executor-none = []

defmt = [
  "embassy-net?/defmt",
  "embassy-time?/defmt",
  "embassy-usb?/defmt",
  "ariel-os-hal/defmt",
  "ariel-os-embassy-common/defmt",
  "trouble-host?/defmt",
  "usbd-hid?/defmt",
]
log = ["ariel-os-hal/log"]

_test = ["dhcpv4", "executor-none", "i2c", "spi", "time", "external-interrupts"]
