name: PR dependencies

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types: [opened, edited, closed, reopened]
  pull_request:
    types: [synchronize]
  merge_group:

permissions: {}

jobs:
  check_dependencies:
    if: github.event_name != 'merge_group'
    runs-on: ubuntu-latest
    name: Check
    steps:
      - uses: gregsdennis/dependencies-action@a8cccab69814b9b985496cf97cbfe154c96c03c7 # main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
