name: PR title checks

on:
  pull_request:
    types: [opened, edited, reopened]

permissions: {}

jobs:
  pr-title:
    name: Lint PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install committed
        uses: taiki-e/install-action@74e87cbfa15a59692b158178d8905a61bf6fca95 # v2
        with:
          tool: committed

      - run: committed --config committed.toml --commit-file <(echo "${PR_TITLE}")
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
