name: Dependency Vetting
on:
  pull_request:
    branches:
      - main
  merge_group:

permissions: {}

jobs:
  cargo-vet:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # master
        with:
          toolchain: 1.95

      - name: Install cargo-vet
        uses: taiki-e/install-action@74e87cbfa15a59692b158178d8905a61bf6fca95 # v2
        with:
          tool: cargo-vet@0.10.2

      - name: Invoke cargo-vet
        run: cargo vet --locked
