name: Dependency Vetting
on:
  pull_request:
    branches:
      - main
  merge_group:

permissions: {}

jobs:
  cargo-vet:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@d1031067263f94b142dd6c0ce24c5eb9d02d52a0 # master
        with:
          toolchain: 1.95

      - name: Install cargo-vet
        uses: taiki-e/install-action@b20dedce73af6905cdc30d6611090c9b67557c8d # v2
        with:
          tool: cargo-vet@0.10.2

      - name: Invoke cargo-vet
        run: cargo vet --locked
